name: Build RPM Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm rpmbuild gcc make

    - name: Create source tarball
      run: |
        tar czf clevo-keyboard-backlight-1.0.tar.gz --transform 's,^,clevo-keyboard-backlight-1.0/,' *

    - name: Build RPM package
      run: |
        rpmbuild -ba --define "_sourcedir $PWD" --define "_specdir $PWD" --define "_builddir $PWD" --define "_srcrpmdir $PWD" --define "_rpmdir $PWD" rpm_pkg.spec

    - name: List built RPMs
      run: find . -name "*.rpm"

    - name: Upload RPM
      uses: actions/upload-artifact@v2
      with:
        name: clevo-keyboard-rpm
        path: ./*.rpm
