name: Build RPM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm build-essential

    - name: Build RPM package
      run: |
        mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        cp src_pkg/rpm_pkg.spec ~/rpmbuild/SPECS/
        cp -r * ~/rpmbuild/SOURCES/
        rpmbuild -ba ~/rpmbuild/SPECS/rpm_pkg.spec

    - name: Upload RPM
      uses: actions/upload-artifact@v2
      with:
        name: clevo-keyboard-rpm
        path: ~/rpmbuild/RPMS/x86_64/*.rpm

    - name: Upload SRPM
      uses: actions/upload-artifact@v2
      with:
        name: clevo-keyboard-srpm
        path: ~/rpmbuild/SRPMS/*.rpm
