name: Build RPM Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build RPM package
      id: rpm
      uses: naveenrajm7/rpmbuild@master
      with:
        spec_file: "rpm_pkg.spec"

    - name: Upload RPM
      uses: actions/upload-artifact@v2
      with:
        name: clevo-keyboard-rpm
        path: ${{ steps.rpm.outputs.rpm_dir_path }}

    - name: Upload SRPM
      uses: actions/upload-artifact@v2
      with:
        name: clevo-keyboard-srpm
        path: ${{ steps.rpm.outputs.source_rpm_path }}
